import test from "node:test";
import assert from "node:assert/strict";
import { detectSegments, activeSegment } from "../core/skip-segments.mjs";
import {
  HOTKEY_ACTIONS,
  validBinding,
  resolveBindings,
  findConflicts,
  inputConf,
  publicHotkeys,
} from "../core/hotkeys.mjs";
import { playerArgs } from "../electron/player.mjs";
import { DEFAULT_SETTINGS } from "../core/protocol.mjs";

test("named chapters produce recap, intro and outro segments", () => {
  const segments = detectSegments({
    chapters: [
      { time: 0, title: "Recap" },
      { time: 45, title: "Opening Credits" },
      { time: 135, title: "Episode" },
      { time: 1300, title: "Ending" },
    ],
    duration: 1400,
  });
  assert.deepEqual(
    segments.map((s) => [s.kind, s.start, s.end]),
    [
      ["recap", 0, 45],
      ["intro", 45, 135],
      ["outro", 1300, 1400],
    ],
  );
  assert.ok(segments.every((s) => s.source === "chapter"));
});

test("Arabic chapter titles are recognised", () => {
  const segments = detectSegments({
    chapters: [
      { time: 0, title: "شارة البداية" },
      { time: 90, title: "الحلقة" },
    ],
    duration: 1500,
  });
  assert.equal(segments[0].kind, "intro");
});

test("without titles the shape of the chapters is used, conservatively", () => {
  const segments = detectSegments({
    chapters: [
      { time: 0, title: "Chapter 1" },
      { time: 30, title: "Chapter 2" },
      { time: 120, title: "Chapter 3" },
      { time: 1350, title: "Chapter 4" },
    ],
    duration: 1420,
  });
  assert.deepEqual(
    segments.map((s) => s.kind),
    ["intro", "outro"],
  );
  assert.ok(segments.every((s) => s.source === "shape"));
  // A first chapter that starts late is not an intro candidate.
  assert.deepEqual(
    detectSegments({
      chapters: [
        { time: 600, title: "A" },
        { time: 700, title: "B" },
      ],
      duration: 1400,
    }).map((s) => s.kind),
    [],
  );
});

test("no chapters and no duration means no guessing", () => {
  assert.deepEqual(detectSegments({}), []);
  assert.deepEqual(
    detectSegments({ chapters: [], duration: 1400, heuristics: false }),
    [],
  );
});

test("a segment is offered only while there is something left to skip", () => {
  const segments = detectSegments({
    chapters: [
      { time: 45, title: "Intro" },
      { time: 135, title: "Part" },
    ],
    duration: 1400,
  });
  assert.equal(activeSegment(segments, 20, {}), null);
  assert.equal(activeSegment(segments, 60, {}).kind, "intro");
  assert.equal(activeSegment(segments, 60, {}).remaining, 75);
  // Inside the last three seconds the button would do nothing.
  assert.equal(activeSegment(segments, 133, {}), null);
  assert.equal(activeSegment(segments, 60, { skipIntro: "off" }), null);
});

test("outro skipping stays off until it is asked for", () => {
  const segments = detectSegments({
    chapters: [
      { time: 0, title: "Show" },
      { time: 1300, title: "End Credits" },
    ],
    duration: 1400,
  });
  assert.equal(activeSegment(segments, 1320, {}), null);
  assert.equal(
    activeSegment(segments, 1320, { skipOutro: "button" }).kind,
    "outro",
  );
});

test("hotkey bindings accept MPV syntax and reject the rest", () => {
  for (const binding of [
    "SPACE",
    "Ctrl+p",
    "Shift+LEFT",
    "f",
    ">",
    "MBTN_LEFT_DBL",
    "F11",
  ])
    assert.equal(validBinding(binding), true, binding);
  for (const binding of [
    "",
    "Hyper+p",
    "NOTAKEY",
    "ctrl+p",
    42,
    "a".repeat(60),
  ])
    assert.equal(validBinding(binding), false, String(binding));
});

test("the shipped defaults do not collide", () => {
  assert.deepEqual(findConflicts(resolveBindings({})), []);
  assert.equal(Object.keys(resolveBindings({})).length, HOTKEY_ACTIONS.length);
});

test("an invalid override falls back to the default binding", () => {
  const bindings = resolveBindings({ playPause: "Hyper+z", mute: "Ctrl+m" });
  assert.equal(bindings.playPause, "SPACE");
  assert.equal(bindings.mute, "Ctrl+m");
});

test("conflicts are reported to the settings view", () => {
  const listing = publicHotkeys({ mute: "SPACE" });
  const affected = listing
    .filter((entry) => entry.conflict)
    .map((entry) => entry.id);
  assert.deepEqual(affected.sort(), ["mute", "playPause"]);
  assert.equal(listing.find((entry) => entry.id === "mute").isDefault, false);
});

test("input.conf renders every action and the pointer gesture", () => {
  const conf = inputConf({ playPause: "Ctrl+p" });
  assert.ok(conf.startsWith("# Generated by Riwaq"));
  assert.ok(conf.includes("Ctrl+p cycle pause"));
  assert.ok(!conf.includes("SPACE cycle pause"));
  assert.ok(conf.includes("MBTN_LEFT_DBL script-message riwaq-fullscreen"));
  assert.ok(conf.includes("MBTN_RIGHT script-message riwaq-panel"));
  // The header, every action, and the two pointer gestures.
  assert.equal(conf.trim().split("\n").length, HOTKEY_ACTIONS.length + 3);
});

test("picture profiles add MPV scaler options and nothing else", () => {
  const base = playerArgs({
    pipe: "p",
    settings: DEFAULT_SETTINGS,
    url: "https://a.test/v",
    title: "t",
  });
  assert.ok(!base.some((arg) => arg.startsWith("--scale=")));
  const anime = playerArgs({
    pipe: "p",
    settings: { ...DEFAULT_SETTINGS, shader: "anime" },
    url: "https://a.test/v",
    title: "t",
  });
  assert.ok(anime.includes("--scale=ewa_lanczossharp"));
  assert.ok(anime.includes("--deband=yes"));
  // An unknown profile name must not reach MPV.
  const bogus = playerArgs({
    pipe: "p",
    settings: { ...DEFAULT_SETTINGS, shader: "rm -rf" },
    url: "https://a.test/v",
    title: "t",
  });
  assert.ok(!bogus.some((arg) => arg.includes("rm -rf")));
});

test("a custom shader path is only passed with the custom profile", () => {
  const withPath = playerArgs({
    pipe: "p",
    settings: {
      ...DEFAULT_SETTINGS,
      shader: "custom",
      shaderPath: "C:/shaders/a.glsl",
    },
    url: "https://a.test/v",
    title: "t",
  });
  assert.ok(withPath.includes("--glsl-shaders=C:/shaders/a.glsl"));
  const ignored = playerArgs({
    pipe: "p",
    settings: {
      ...DEFAULT_SETTINGS,
      shader: "anime",
      shaderPath: "C:/shaders/a.glsl",
    },
    url: "https://a.test/v",
    title: "t",
  });
  assert.ok(!ignored.some((arg) => arg.startsWith("--glsl-shaders=")));
});

test("live sources buffer and reconnect instead of ending", () => {
  const args = playerArgs({
    pipe: "p",
    settings: { ...DEFAULT_SETTINGS, liveBufferSeconds: 8 },
    url: "https://a.test/live.m3u8",
    title: "t",
    live: true,
  });
  assert.ok(args.includes("--cache-secs=8"));
  assert.ok(args.includes("--keep-open=yes"));
  assert.ok(args.some((arg) => arg.startsWith("--stream-lavf-o=reconnect=1")));
  assert.deepEqual(args.slice(-2), ["--", "https://a.test/live.m3u8"]);
});

test("tone mapping only forwards names MPV knows", () => {
  const good = playerArgs({
    pipe: "p",
    settings: { ...DEFAULT_SETTINGS, toneMapping: "bt.2446a" },
    url: "https://a.test/v",
    title: "t",
  });
  assert.ok(good.includes("--tone-mapping=bt.2446a"));
  const off = playerArgs({
    pipe: "p",
    settings: { ...DEFAULT_SETTINGS, toneMapping: "off" },
    url: "https://a.test/v",
    title: "t",
  });
  assert.ok(!off.some((arg) => arg.startsWith("--tone-mapping=")));
  const bogus = playerArgs({
    pipe: "p",
    settings: { ...DEFAULT_SETTINGS, toneMapping: "auto" },
    url: "https://a.test/v",
    title: "t",
  });
  assert.ok(!bogus.some((arg) => arg.startsWith("--tone-mapping=")));
});
