const { contextBridge, ipcRenderer } = require("electron");
const allowed = new Set([
  "init",
  "windowInfo",
  "windowControl",
  "windowDrag",
  "relaunch",
  "setAppIcon",
  "catalog",
  "catalogPlan",
  "subtitleCues",
  "copyThemeCode",
  "copyBadgePack",
  "debridSave",
  "debridCheck",
  "watchProviders",
  "serviceRows",
  "homeServerAdd",
  "homeServerRemove",
  "homeServerToggle",
  "homeServerCheck",
  "streamServerInfo",
  "streamServerSave",
  "hudPanel",
  "hudRequest",
  "hudIdle",
  "titleCredits",
  "creditsEntity",
  "searchPeople",
  "collectionsEdit",
  "collectionCatalogs",
  "collectionFolder",
  "collectionSource",
  "collectionsCopyNuvio",
  "collectionsSaveNuvio",
  "importNuvioCollections",
  "nuvioScan",
  "nuvioPickBackup",
  "nuvioImport",
  "nuvioDiagnostics",
  "removeNuvioPlugin",
  "openTrailer",
  "playerSources",
  "switchSource",
  "metadata",
  "streams",
  "subtitles",
  "install",
  "updateAddon",
  "settings",
  "favorite",
  "queueEdit",
  "historyEdit",
  "episodes",
  "login",
  "cancelLogin",
  "logout",
  "sync",
  "configure",
  "play",
  "videoBounds",
  "providerSave",
  "providerTest",
  "integrationSave",
  "integrationSync",
  "integrationDisconnect",
  "traktLogin",
  "traktPoll",
  "letterboxdImport",
  "openService",
  "playerCommand",
  "trickplay",
  "stop",
  "subtitle",
  "localSubtitle",
  "localVideo",
  "choosePlayer",
  "diagnostics",
  "exportAddons",
  "importAddons",
  "profileCreate",
  "profileUpdate",
  "profileRemove",
  "profileSwitch",
  "profilePin",
  "profileUnlock",
  "profileLock",
  "setHotkey",
  "resetHotkeys",
  "notifySave",
  "notifyTest",
  "presenceSave",
  "liveAdd",
  "liveUpdate",
  "liveRefresh",
  "liveChannels",
  "liveGuide",
  "liveFavorite",
  "playChannel",
  "openScreenshots",
  "chooseShader",
  "updatesCheck",
  "updatesSetEnabled",
  "updatesConfigure",
  "updatesDownload",
  "updatesCancel",
  "updatesInstall",
  "openUpdate",
  "backupExport",
  "backupPick",
  "backupPreview",
  "backupRestore",
  "backupCancel",
]);
contextBridge.exposeInMainWorld("riwaq", {
  call: async (method, args) => {
    if (!allowed.has(method)) throw new Error("Unknown action");
    const r = await ipcRenderer.invoke("riwaq", method, args);
    if (!r.ok) throw new Error(r.error);
    return r.value;
  },
  on: (name, fn) => {
    if (
      ![
        "state",
        "player",
        "notice",
        "ended",
        "playerRequest",
        "hudCommand",
        "window",
      ].includes(name)
    )
      return () => {};
    const handler = (_event, data) => fn(data);
    ipcRenderer.on("riwaq:" + name, handler);
    return () => ipcRenderer.removeListener("riwaq:" + name, handler);
  },
});
